### Test
GET https://tiger-crunch.com:4433

### Authenticate
POST https://tiger-crunch.com:4433/auth HTTP/1.1
content-type: application/json

{
    "claims" : 
    {   
        "email": "paulsembereka@zohomail.eu",
        "proposedPIN": "1234",
        "otp":"603393"
    }
}

### Register
POST https://tiger-crunch.com:4433/users HTTP/1.1
content-type: application/json

{
    "name":"Paul Sembereka", 
    "email":"paulsembereka@zohomail.eu",
    "phone":"12345678",
    "proposedPIN":"1234"
}

### Register 2fa

POST https://tiger-crunch.com:4433/auth/2fa HTTP/1.1
content-type: application/json

{
    "proposedPIN":"1234"
}

### Verify 2fa
POST https://tiger-crunch.com:4433/auth/2fa/verify HTTP/1.1
content-type: application/json
{
    "otp":"603393"
}

## Clients
### register client
POST https://tiger-crunch.com:4433/clients HTTP/1.1
content-type: application/json

{
    "email":"findyourcat@app.com",
    "project_name":"findyourcat",
    "domain":"https://findyourcat.com/v1/callback"
}

### verify client
GET https://tiger-crunch.com:4433/clients/verify HTTP/1.1
content-type: application/json

{
    "client_id": "bd7e5e97-afe4-4796-b757-690ddc79ebb2",
    "client_secret": "p4ETQXS1qpoMyiSdWhzjF6fz-u7ot2hD47ZQuCGwuG0="
}

## OAuth grant routes
### request code 
GET https://tiger-crunch.com:4433/auth/code
?response_type=code
&scope=openid%20profile%20email
&client_id=bd7e5e97-afe4-4796-b757-690ddc79ebb2
&state=af0ifjsldkj
&redirect_uri=https%3A%2F%2Ffindyourcat.com HTTP/1.1

### request token
POST https://tiger-crunch.com:4433/auth/token
?grant_type=authorization_code
&code=zZdf2eEfdZNhlJfnJnG2pAyj29hCgQF2PSoySA6S9wI=
&redirect_uri=https%3A%2F%2Ffindyourcat.com HTTP/1.1
Authorization: Basic bd7e5e97-afe4-4796-b757-690ddc79ebb2:p4ETQXS1qpoMyiSdWhzjF6fz-u7ot2hD47ZQuCGwuG0=
### implicit flow
GET https://tiger-crunch.com:4433/auth/implicit
?response_type=id_token%20token 
&client_id=s6BhdRkqt3
&redirect_uri=https%3A%2F%2Fclient.example.org%2Fcb
&scope=openid%20profile
&state=af0ifjsldkj
&nonce=n-0S6_WzA2Mj HTTP/1.1

### hybrid flow
GET https://tiger-crunch.com:4433/auth/hybrid
?response_type=code%20id_token
&client_id=s6BhdRkqt3
&redirect_uri=https%3A%2F%2Fclient.example.org%2Fcb
&scope=openid%20profile%20email
&nonce=n-0S6_WzA2Mj
&state=af0ifjsldkj HTTP/1.1

### refresh token
POST https://tiger-crunch.com:4433/auth/refresh-token
?grant_type=refresh_token
&refresh_token=-bY53NrSLwnYXbTbnBcO5_ib6-KS3L5BvgpB_VclitQ=
&scope=openid%20profile HTTP/1.1
Authorization: Basic bd7e5e97-afe4-4796-b757-690ddc79ebb2:p4ETQXS1qpoMyiSdWhzjF6fz-u7ot2hD47ZQuCGwuG0=

### introspection
POST https://tiger-crunch.com:4433/auth/introspection
?token=IwdSIOeV6L8uRmaeeYYI9mtEmWlpUdmPypsnv-psmaw=
&token_hint=access_token HTTP/1.1
Authorization: Basic bd7e5e97-afe4-4796-b757-690ddc79ebb2:p4ETQXS1qpoMyiSdWhzjF6fz-u7ot2hD47ZQuCGwuG0=
