# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: UnitTests CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js ⚙️
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Setup npm
      run: | # Custom action
        npm set @smembe812:registry=https://npm.pkg.github.com/
        npm set "//npm.pkg.github.com/:_authToken=$secrets.GAT"
    - name: Setup lerna
      run: | # Install and link dependencies
        npm install lerna -g
        lerna clean -y
        lerna link
        lerna bootstrap
    - name: Run unit tests # Run tests of all packages
      run: npm run test:unit --workspaces --if-present
     
   

